package db

import (
	"context"

	dbgen "ginbar/db/gen"
)

// ── Import-specific DB helpers (not generated by sqlc) ────────────────────────

// FilterExistingURLs returns a set of the given URLs that already exist in
// posts (including dirty/pending rows).  This is the fast batch dedup check
// run before inserting dirty placeholder rows.
func (s *Store) FilterExistingURLs(ctx context.Context, urls []string) (map[string]bool, error) {
	if len(urls) == 0 {
		return map[string]bool{}, nil
	}
	rows, err := s.Pool.Query(ctx,
		`SELECT url FROM posts WHERE url = ANY($1::text[]) AND deleted_at IS NULL`,
		urls,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	existing := make(map[string]bool, len(urls))
	for rows.Next() {
		var u string
		if err := rows.Scan(&u); err != nil {
			return nil, err
		}
		existing[u] = true
	}
	return existing, rows.Err()
}

// CreateDirtyPost inserts a placeholder post row with dirty=true.
// filename, thumbnail_filename, content_type, and phashes are left at their
// zero values; they will be filled in by FinalizePost once the image has been
// downloaded and processed.
func (s *Store) CreateDirtyPost(ctx context.Context, url, userName string) (dbgen.Post, error) {
	const q = `
INSERT INTO posts (url, user_name, filename, thumbnail_filename, content_type, dirty)
VALUES ($1, $2, '', '', 'image', TRUE)
RETURNING id, url, uploaded_filename, filename, thumbnail_filename, content_type,
          score, user_level, p_hash_0, p_hash_1, p_hash_2, p_hash_3,
          user_name, created_at, deleted_at, dirty
`
	row := s.Pool.QueryRow(ctx, q, url, userName)
	var p dbgen.Post
	err := row.Scan(
		&p.ID,
		&p.Url,
		&p.UploadedFilename,
		&p.Filename,
		&p.ThumbnailFilename,
		&p.ContentType,
		&p.Score,
		&p.UserLevel,
		&p.PHash0,
		&p.PHash1,
		&p.PHash2,
		&p.PHash3,
		&p.UserName,
		&p.CreatedAt,
		&p.DeletedAt,
		&p.Dirty,
	)
	return p, err
}

// FinalizePostParams holds the data needed to promote a dirty post to clean.
type FinalizePostParams struct {
	ID                int32
	Filename          string
	ThumbnailFilename string
	UploadedFilename  string
	ContentType       string
	PHash0            int64
	PHash1            int64
	PHash2            int64
	PHash3            int64
}

// FinalizePost sets all file/hash fields on a dirty post and clears the dirty
// flag, making the post visible in normal feeds.
func (s *Store) FinalizePost(ctx context.Context, arg FinalizePostParams) error {
	const q = `
UPDATE posts
SET filename           = $1,
    thumbnail_filename = $2,
    uploaded_filename  = $3,
    content_type       = $4,
    p_hash_0           = $5,
    p_hash_1           = $6,
    p_hash_2           = $7,
    p_hash_3           = $8,
    dirty              = FALSE
WHERE id = $9
`
	_, err := s.Pool.Exec(ctx, q,
		arg.Filename,
		arg.ThumbnailFilename,
		arg.UploadedFilename,
		arg.ContentType,
		arg.PHash0,
		arg.PHash1,
		arg.PHash2,
		arg.PHash3,
		arg.ID,
	)
	return err
}

// DeleteDirtyPost removes a post that failed processing so the URL will not be
// permanently blocked from future imports.
func (s *Store) DeleteDirtyPost(ctx context.Context, id int32) error {
	const q = `DELETE FROM posts WHERE id = $1 AND dirty = TRUE`
	_, err := s.Pool.Exec(ctx, q, id)
	return err
}

// GetDirtyPosts returns all dirty posts (for diagnostics / resumable imports).
func (s *Store) GetDirtyPosts(ctx context.Context) ([]dbgen.Post, error) {
	const q = `
SELECT id, url, uploaded_filename, filename, thumbnail_filename, content_type,
       score, user_level, p_hash_0, p_hash_1, p_hash_2, p_hash_3,
       user_name, created_at, deleted_at, dirty
FROM posts WHERE dirty = TRUE AND deleted_at IS NULL ORDER BY id
`
	rows, err := s.Pool.Query(ctx, q)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var items []dbgen.Post
	for rows.Next() {
		var p dbgen.Post
		if err := rows.Scan(
			&p.ID, &p.Url, &p.UploadedFilename, &p.Filename, &p.ThumbnailFilename,
			&p.ContentType, &p.Score, &p.UserLevel,
			&p.PHash0, &p.PHash1, &p.PHash2, &p.PHash3,
			&p.UserName, &p.CreatedAt, &p.DeletedAt, &p.Dirty,
		); err != nil {
			return nil, err
		}
		items = append(items, p)
	}
	return items, rows.Err()
}
