-- +goose Up
ALTER TABLE posts ADD COLUMN width INT NOT NULL DEFAULT 0;
ALTER TABLE posts ADD COLUMN height INT NOT NULL DEFAULT 0;

-- +goose Down
ALTER TABLE posts DROP COLUMN IF EXISTS width;
ALTER TABLE posts DROP COLUMN IF EXISTS height;
